# Generated by Django 6.0.7 on 2026-08-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('cargo', models.CharField(choices=[('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Operario', 'Operario'), ('Contador', 'Contador'), ('Auxiliar', 'Auxiliar')], max_length=30)),
                ('area', models.CharField(choices=[('Gerencia', 'Gerencia'), ('Operaciones', 'Operaciones'), ('Recursos Humanos', 'Recursos Humanos'), ('Seguridad Industrial', 'Seguridad Industrial'), ('Finanzas', 'Finanzas'), ('Logística', 'Logística')], max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Vacaciones', 'Vacaciones'), ('Inactivo', 'Inactivo')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombres'],
            },
        ),
    ]
