# Generated by Django 6.0.7 on 2026-08-06 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombres', 'apellidos']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['empresa']},
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Vacaciones', 'Vacaciones'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
    ]
