# Generated by Django 6.0.7 on 2026-08-28 04:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_venta_detalleventa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['id'], 'verbose_name': 'detalle de venta', 'verbose_name_plural': 'detalles de venta'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombres', 'apellidos'], 'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['empresa'], 'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha'], 'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
