# Generated by Django 6.0.7 on 2026-09-21 04:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_cliente_options_alter_detalleventa_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("Manana", "Mañana (6:00 - 14:00)"),
                            ("Tarde", "Tarde (14:00 - 22:00)"),
                            ("Noche", "Noche (22:00 - 6:00)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("Marmol", "Mármol"),
                            ("Caliza", "Caliza"),
                            ("Recebo", "Recebo"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[("t", "Toneladas (t)"), ("m3", "Metros cúbicos (m³)")],
                        default="t",
                        max_length=2,
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("5000")),
                        ],
                    ),
                ),
                ("observaciones", models.CharField(blank=True, max_length=300)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="producciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producciones",
                        to="core.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de producción",
                "verbose_name_plural": "registros de producción",
                "ordering": ["-fecha", "turno", "material"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fecha", "turno", "material"),
                        name="produccion_unica_por_turno",
                        violation_error_message="Ya existe un registro de ese material para ese turno y esa fecha.",
                    )
                ],
            },
        ),
    ]
